### ISSUE TITLE
Adding repository

### ISSUE THREAD

**Issue by antonio-petricca** [flathub/com.github.bcedu.vgrive#1]
HI, could you kindly provide us the instructions to add your repo to our system?

Thank you so much!

**Comment by bcedu** [comment]
Do you mean with "add your repo"? adding an apt repository?

Also, what is your system?

Thanks.

**Comment by antonio-petricca** [comment]
I am on Ubuntu, and would address you flatpak application package...

Thank you!

**Comment by bilelmoussaoui** [comment]
Just follow the steps from here https://flatpak.org/setup/ and install it from here https://flathub.org/apps/details/com.github.bcedu.vgrive.
